CREATE TABLE "doors"(
    "door_id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "required_access_level" INTEGER NOT NULL,
    CONSTRAINT pk_doors PRIMARY KEY(doors(door_id))
);

CREATE TABLE "roles"(
    "role_id" BIGINT NOT NULL,
    "role_name" VARCHAR(255) NOT NULL,
    "access_level" BIGINT NOT NULL
);

ALTER TABLE
    "roles" ADD PRIMARY KEY("role_id");
ALTER TABLE
    "roles" ADD CONSTRAINT "roles_role_name_unique" UNIQUE("role_name");
ALTER TABLE
    "roles" ADD CONSTRAINT "roles_access_level_unique" UNIQUE("access_level");
CREATE TABLE "users"(
    "user_id" BIGINT NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "email" VARCHAR(255) NOT NULL,
    "role_id" BIGINT NOT NULL
);
ALTER TABLE
    "users" ADD PRIMARY KEY("user_id");
ALTER TABLE
    "users" ADD CONSTRAINT "users_email_unique" UNIQUE("email");
CREATE INDEX "users_role_id_index" ON
    "users"("role_id");
CREATE TABLE "passes"(
    "pass_id" BIGINT NOT NULL,
    "pass_datetime" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    "user_id" BIGINT NOT NULL,
    "door_id" BIGINT NOT NULL
);
ALTER TABLE
    "passes" ADD PRIMARY KEY("pass_id");
CREATE INDEX "passes_user_id_index" ON
    "passes"("user_id");
CREATE INDEX "passes_door_id_index" ON
    "passes"("door_id");
ALTER TABLE
    "passes" ADD CONSTRAINT "passes_user_id_foreign" FOREIGN KEY("user_id") REFERENCES "users"("user_id");
ALTER TABLE
    "passes" ADD CONSTRAINT "passes_door_id_foreign" FOREIGN KEY("door_id") REFERENCES "doors"("door_id");
ALTER TABLE
    "users" ADD CONSTRAINT "users_role_id_foreign" FOREIGN KEY("role_id") REFERENCES "roles"("role_id");
