server:
  address: localhost
  port: 8080

spring:
  config:
    activate:
      on-profile: default, prod
  datasource:
    password: "kitty"
    username: "kitty"
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/rfid-db"

---

spring:
  datasource:
    driver-class-name: org.h2.Driver
    generate-unique-name: true
    username: "SA"
    password: ""

  config:
    activate:
      on-profile: test

logging:
  level:
    sql: info
